### PR TITLE
Introduce FetchedSQLRow

### PR DESCRIPTION
**Pull request by ahmedk92**
This PR introduces a different raw row type other than `SQLRow`. `SQLRow` relies on a live statement that can change upon calling `step()` thus changing returned values if called on a row that had other subsequent rows fetched.

I also added two methods `row()` and `rows(count:)` to `SQLStatement` that return `FetchedSQLRow?` and `[FetchedSQLRow]` respectively.

These addition combined can be useful for instantiating types indirectly from a SQL result without conforming to `SQLRowDecodable`. Some types cannot provide such conformance because it depends on another value upon instantiation, for example:

```swift
struct Cat: Hashable {
    var name: String
    var age: Float
    var owner: Person
}
```

While `name` and `age` can be obtained from a SQL result, there's an `owner` dependency that isn't. By having the ability to fetch stateless rows, we can use each fetch rows to instantiate a corresponding set with the other dependency. 

```swift

let cats = try db
            .prepare("SELECT Name, Age FROM Cats ORDER BY Age ASC")
            .rows()
            .map({ Cat(row: $0, owner: owner) })

extension Cat {
    init(row: FetchedSQLRow, owner: Person) {
        name = row["Name"]
        age = row["Age"]
        self.owner = owner
    }
}
```

This addition requires `SQLDataType` to provide an implementation for a new method to convert from SQLite types. Namely:

`static func convert(from variant: SQLVariant) -> Self?`

I added the needed tests and default conversions for common types.

Thanks!

### CODE REVIEW

**Comment by kean** [comment]
H @ahmedk92, sorry for not getting back to you earlier. 

I think this is a good addition, I'm just not sure about the name `SQLVariant` and the need for  `convert(from variant: SQLVariant)` to be part of the core library – the goal of it is to be as simple and as thin wrapper on top of SQLite as possible. Otherwise, I'm OK merging it and again I appreciate your contribution.

**Comment by kean** [comment]
I'm also thinking whether it makes sense to incorporate `FetchedSQLRow` into the existing `SQLRow`. I should've probably just left my "extensions" out of this library 😅

**Comment by ahmedk92** [comment]
No worries, I see you're so busy :)

Incorporating the copy semantics of `FetchedSQLRow` into `SQLRow` involves reading and storing all column values upon instantiating, in advance before any column access. So, reading column values at an early stage like this cause the loss of the type information; i.e. we need then to store column values as `Any`, then types conforming to `SQLDataType` are required to offer a conversion from `Any`. In code in case it's not clear:

Instead of this in `SQLDataType` protocol
```swift
static func sqlColumn(statement: OpaquePointer, index: Int32) -> Self
```
We'll need something like this:

```swift
static func convert(value: Any) -> Self
```

I just wanted these semantics to be opt-in (and additive) without so much surprises.

`SQLVariant` is just a fancy way to represent what can be represented by `Any` while knowing the limited set of values to convert from (i.e. those that can be obtained by `sqlite3_column_type`).

I know features are creeping through SQLExt, but using other libraries I really needed an intermediate row type for cases like the example in my first post (i.e. when I cannot instantiate my object only from a sql row). I can promise this is the last feature (I have a SQLCipher support intention; but I'm already thinking it should be another library/module 🤭)

Thanks for your reply!

**Comment by kean** [comment]
What I was thinking, maybe it worth reading all of the columns upfront, storing them in an array as `SQLVariant`, and then, when the user calls `public subscript<T: SQLDataType>(index: Int) -> T`, returning the value from the array instead of going to the database. This is going to add a bit of a performance overhead (I'm wondering how much?), but it will "fix" the leaky `SQLRow` abstraction where it's not really a value type. What you you think, does it make sense?

**Comment by ahmedk92** [comment]
Sounds good to me! But `SQLDataType` will no longer have the `static func sqlColumn(statement: OpaquePointer, index: Int32) -> Self` requirement, and instead will have a conversion from `SQLVariant` or `Any` requirement. I can make two PRs (one with `SQLVariant` and one with `Any`) and let you decide.

**Comment by ahmedk92** [comment]
Ignore most of my last reply :) I got carried away and too focused on the feature and forgot the usage of `SQLStatement` on its own 🤦‍♂️

I'm preparing a good PR with little and much less intrusive changes.

**Comment by ahmedk92** [comment]
Done. https://github.com/kean/SwiftSQL/pull/6

**Comment by ahmedk92** [comment]
Thank you for accepting the other PR. I think this one is not valid anymore; I’ll close it.

**Pull request closed without merging**
